#!/bin/sh

# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
#

# This script removes the route to the PPPoE client.
ip route del "$PPP_REMOTE" dev "$PPP_IFACE"
